# These are supported funding model GitHub sponsors

github: arg9244

# You can also support the project through other platforms
# patreon: patreon_username
# open_collective: open_collective_username
# kofi: kofi_username
# custom: ["https://example.com"]